CREATE TABLE organizations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE CHECK (length(trim(name)) > 1),
    kind text NOT NULL CHECK (kind IN ('local_ngo','international_ngo','public_agency','community_group','other')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE CHECK (email = lower(trim(email))),
    full_name text NOT NULL CHECK (length(trim(full_name)) BETWEEN 2 AND 120),
    password_hash text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE organization_memberships (
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('org_admin','editor','reviewer','viewer')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, organization_id)
);

CREATE TABLE responses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code text NOT NULL UNIQUE CHECK (code ~ '^[A-Z0-9-]{3,40}$'),
    title text NOT NULL CHECK (length(trim(title)) BETWEEN 3 AND 160),
    location text NOT NULL CHECK (length(trim(location)) BETWEEN 2 AND 120),
    summary text NOT NULL CHECK (length(trim(summary)) BETWEEN 10 AND 1000),
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','in_review','approved','closed')),
    start_date date,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE funding_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    source_type text NOT NULL CHECK (source_type IN ('manual','csv_import','blockchain','payment_report'))
);

CREATE TABLE import_batches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    source_name text NOT NULL,
    file_name text NOT NULL,
    rows_received integer NOT NULL DEFAULT 0 CHECK (rows_received >= 0),
    rows_imported integer NOT NULL DEFAULT 0 CHECK (rows_imported >= 0),
    rows_skipped integer NOT NULL DEFAULT 0 CHECK (rows_skipped >= 0),
    status text NOT NULL CHECK (status IN ('completed','completed_with_skips')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE funding_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id bigint NOT NULL REFERENCES responses(id) ON DELETE RESTRICT,
    source_id bigint NOT NULL REFERENCES funding_sources(id) ON DELETE RESTRICT,
    import_batch_id bigint REFERENCES import_batches(id) ON DELETE RESTRICT,
    record_type text NOT NULL CHECK (record_type IN ('contribution','disbursement')),
    amount numeric(18,2) NOT NULL CHECK (amount > 0),
    currency char(3) NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
    recorded_on date NOT NULL,
    reference text NOT NULL CHECK (length(trim(reference)) BETWEEN 3 AND 120),
    description text,
    source_reference text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(response_id,source_id,source_reference)
);

CREATE TABLE reconciliation_issues (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id bigint NOT NULL REFERENCES responses(id) ON DELETE RESTRICT,
    funding_record_id bigint REFERENCES funding_records(id) ON DELETE RESTRICT,
    issue_type text NOT NULL CHECK (issue_type IN ('missing_reference','possible_duplicate','amount_mismatch','needs_review')),
    description text NOT NULL,
    status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','resolved')),
    created_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,
    CHECK ((status='open' AND resolved_at IS NULL) OR (status='resolved' AND resolved_at IS NOT NULL))
);

CREATE TABLE audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id bigint NOT NULL,
    actor_label text NOT NULL,
    details jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX responses_org_status_idx ON responses(organization_id,status);
CREATE INDEX memberships_org_role_idx ON organization_memberships(organization_id,role);
CREATE INDEX import_batches_org_created_idx ON import_batches(organization_id,created_at DESC);
CREATE INDEX funding_records_response_date_idx ON funding_records(response_id,recorded_on DESC);
CREATE INDEX reconciliation_issues_status_idx ON reconciliation_issues(status,created_at DESC);
CREATE INDEX audit_events_entity_idx ON audit_events(entity_type,entity_id,created_at DESC);

CREATE VIEW response_funding_summary AS
SELECT r.id AS response_id,r.code,r.title,r.status,o.name AS organization_name,
       coalesce(sum(f.amount) FILTER (WHERE f.record_type='contribution'),0)::numeric(18,2) AS contributions,
       coalesce(sum(f.amount) FILTER (WHERE f.record_type='disbursement'),0)::numeric(18,2) AS disbursements,
       count(f.id) AS record_count
FROM responses r JOIN organizations o ON o.id=r.organization_id
LEFT JOIN funding_records f ON f.response_id=r.id
GROUP BY r.id,o.name;

CREATE FUNCTION prevent_audit_event_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Audit events are append-only';
END;
$$;

CREATE TRIGGER audit_events_append_only
BEFORE UPDATE OR DELETE ON audit_events
FOR EACH ROW EXECUTE FUNCTION prevent_audit_event_mutation();

