CREATE TABLE organizations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE CHECK (length(trim(name)) > 1),
    kind text NOT NULL CHECK (kind IN ('local_ngo','international_ngo','public_agency','community_group','other')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE CHECK (email = lower(trim(email))),
    full_name text NOT NULL CHECK (length(trim(full_name)) BETWEEN 2 AND 120),
    password_hash text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Random session secrets are stored as one-way hashes and can be revoked server-side.
CREATE TABLE user_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash char(64) NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    CHECK (expires_at > created_at)
);

-- Keyed by HMAC(email + client address), so raw IPs and submitted addresses are not stored.
CREATE TABLE login_throttles (
    key_hash char(64) PRIMARY KEY,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    window_started_at timestamptz NOT NULL DEFAULT now(),
    blocked_until timestamptz
);

CREATE TABLE organization_memberships (
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('org_admin','editor','reviewer','viewer')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, organization_id)
);

CREATE TABLE responses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code text NOT NULL UNIQUE CHECK (code ~ '^[A-Z0-9-]{3,40}$'),
    title text NOT NULL CHECK (length(trim(title)) BETWEEN 3 AND 160),
    location text NOT NULL CHECK (length(trim(location)) BETWEEN 2 AND 120),
    summary text NOT NULL CHECK (length(trim(summary)) BETWEEN 10 AND 1000),
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','in_review','approved','closed')),
    start_date date,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, organization_id)
);

-- A funder/award/budget/reporting lifecycle, inspired by established grant-management systems.
CREATE TABLE funders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    name text NOT NULL CHECK (length(trim(name)) BETWEEN 2 AND 160),
    kind text NOT NULL CHECK (kind IN ('foundation','government','institutional_donor','corporate','other')),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organization_id, name),
    UNIQUE (id, organization_id)
);

CREATE TABLE funding_awards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    funder_id bigint NOT NULL,
    award_code text NOT NULL CHECK (award_code ~ '^[A-Z0-9-]{3,40}$'),
    title text NOT NULL CHECK (length(trim(title)) BETWEEN 3 AND 160),
    total_amount numeric(18,2) NOT NULL CHECK (total_amount > 0),
    currency char(3) NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
    start_date date NOT NULL,
    end_date date NOT NULL,
    restricted_purpose text NOT NULL CHECK (length(trim(restricted_purpose)) BETWEEN 5 AND 1000),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('draft','active','closed')),
    created_by bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (end_date >= start_date),
    UNIQUE (organization_id, award_code),
    UNIQUE (id, organization_id),
    FOREIGN KEY (funder_id, organization_id) REFERENCES funders(id, organization_id) ON DELETE RESTRICT
);

CREATE TABLE award_allocations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    award_id bigint NOT NULL,
    response_id bigint NOT NULL,
    category text NOT NULL CHECK (length(trim(category)) BETWEEN 2 AND 80),
    budget_amount numeric(18,2) NOT NULL CHECK (budget_amount > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (award_id, response_id, category),
    UNIQUE (id, response_id),
    FOREIGN KEY (award_id, organization_id) REFERENCES funding_awards(id, organization_id) ON DELETE RESTRICT,
    FOREIGN KEY (response_id, organization_id) REFERENCES responses(id, organization_id) ON DELETE RESTRICT
);

CREATE TABLE reporting_milestones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    award_id bigint NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    due_date date NOT NULL,
    report_type text NOT NULL CHECK (report_type IN ('financial','programmatic','closeout')),
    status text NOT NULL DEFAULT 'upcoming' CHECK (status IN ('upcoming','submitted','accepted','needs_revision')),
    summary text,
    submitted_at timestamptz,
    submitted_by bigint REFERENCES users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (period_end >= period_start),
    CHECK ((status IN ('upcoming','needs_revision') AND submitted_at IS NULL) OR (status IN ('submitted','accepted') AND submitted_at IS NOT NULL)),
    UNIQUE (award_id, period_start, period_end, report_type),
    FOREIGN KEY (award_id, organization_id) REFERENCES funding_awards(id, organization_id) ON DELETE RESTRICT
);

CREATE TABLE funding_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    source_type text NOT NULL CHECK (source_type IN ('manual','csv_import','blockchain','payment_report'))
);

CREATE TABLE import_batches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    source_name text NOT NULL,
    file_name text NOT NULL,
    rows_received integer NOT NULL DEFAULT 0 CHECK (rows_received >= 0),
    rows_imported integer NOT NULL DEFAULT 0 CHECK (rows_imported >= 0),
    rows_skipped integer NOT NULL DEFAULT 0 CHECK (rows_skipped >= 0),
    status text NOT NULL CHECK (status IN ('completed','completed_with_skips')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE funding_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id bigint NOT NULL REFERENCES responses(id) ON DELETE RESTRICT,
    award_allocation_id bigint,
    source_id bigint NOT NULL REFERENCES funding_sources(id) ON DELETE RESTRICT,
    import_batch_id bigint REFERENCES import_batches(id) ON DELETE RESTRICT,
    record_type text NOT NULL CHECK (record_type IN ('contribution','disbursement')),
    amount numeric(18,2) NOT NULL CHECK (amount > 0),
    currency char(3) NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
    recorded_on date NOT NULL,
    reference text NOT NULL CHECK (length(trim(reference)) BETWEEN 3 AND 120),
    description text,
    source_reference text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(response_id,source_id,source_reference),
    FOREIGN KEY (award_allocation_id, response_id) REFERENCES award_allocations(id, response_id) ON DELETE RESTRICT
);

CREATE TABLE reconciliation_issues (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id bigint NOT NULL REFERENCES responses(id) ON DELETE RESTRICT,
    funding_record_id bigint REFERENCES funding_records(id) ON DELETE RESTRICT,
    issue_type text NOT NULL CHECK (issue_type IN ('missing_reference','possible_duplicate','amount_mismatch','needs_review')),
    description text NOT NULL,
    status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','resolved')),
    created_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,
    CHECK ((status='open' AND resolved_at IS NULL) OR (status='resolved' AND resolved_at IS NOT NULL))
);

CREATE TABLE audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id bigint NOT NULL,
    actor_label text NOT NULL,
    details jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX responses_org_status_idx ON responses(organization_id,status);
CREATE INDEX memberships_org_role_idx ON organization_memberships(organization_id,role);
CREATE INDEX user_sessions_user_expiry_idx ON user_sessions(user_id,expires_at) WHERE revoked_at IS NULL;
CREATE INDEX award_allocations_award_idx ON award_allocations(award_id,response_id);
CREATE INDEX reporting_milestones_org_due_idx ON reporting_milestones(organization_id,due_date,status);
CREATE INDEX import_batches_org_created_idx ON import_batches(organization_id,created_at DESC);
CREATE INDEX funding_records_response_date_idx ON funding_records(response_id,recorded_on DESC);
CREATE INDEX reconciliation_issues_status_idx ON reconciliation_issues(status,created_at DESC);
CREATE INDEX audit_events_entity_idx ON audit_events(entity_type,entity_id,created_at DESC);

CREATE VIEW response_funding_summary AS
SELECT r.id AS response_id,r.code,r.title,r.status,o.name AS organization_name,
       coalesce(sum(f.amount) FILTER (WHERE f.record_type='contribution'),0)::numeric(18,2) AS contributions,
       coalesce(sum(f.amount) FILTER (WHERE f.record_type='disbursement'),0)::numeric(18,2) AS disbursements,
       count(f.id) AS record_count
FROM responses r JOIN organizations o ON o.id=r.organization_id
LEFT JOIN funding_records f ON f.response_id=r.id
GROUP BY r.id,o.name;

CREATE FUNCTION prevent_audit_event_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Audit events are append-only';
END;
$$;

CREATE TRIGGER audit_events_append_only
BEFORE UPDATE OR DELETE ON audit_events
FOR EACH ROW EXECUTE FUNCTION prevent_audit_event_mutation();

CREATE FUNCTION enforce_award_allocation_limit() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE award_total numeric(18,2); already_allocated numeric(18,2);
BEGIN
    SELECT total_amount INTO award_total FROM funding_awards WHERE id=NEW.award_id FOR UPDATE;
    SELECT coalesce(sum(budget_amount),0) INTO already_allocated FROM award_allocations
      WHERE award_id=NEW.award_id AND id IS DISTINCT FROM NEW.id;
    IF already_allocated + NEW.budget_amount > award_total THEN
        RAISE EXCEPTION 'Award allocations cannot exceed the award total';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER award_allocation_limit
BEFORE INSERT OR UPDATE ON award_allocations
FOR EACH ROW EXECUTE FUNCTION enforce_award_allocation_limit();

CREATE FUNCTION enforce_disbursement_budget() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE allocation_budget numeric(18,2); already_spent numeric(18,2);
BEGIN
    IF NEW.award_allocation_id IS NULL THEN RETURN NEW; END IF;
    IF NEW.record_type <> 'disbursement' THEN
        RAISE EXCEPTION 'Award budget lines can only be used for disbursements';
    END IF;
    SELECT budget_amount INTO allocation_budget FROM award_allocations WHERE id=NEW.award_allocation_id FOR UPDATE;
    SELECT coalesce(sum(amount),0) INTO already_spent FROM funding_records
      WHERE award_allocation_id=NEW.award_allocation_id AND record_type='disbursement' AND id IS DISTINCT FROM NEW.id;
    IF already_spent + NEW.amount > allocation_budget THEN
        RAISE EXCEPTION 'Disbursement would exceed the approved award budget line';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER disbursement_budget_guard
BEFORE INSERT OR UPDATE ON funding_records
FOR EACH ROW EXECUTE FUNCTION enforce_disbursement_budget();
